server:
  error:
    include-message: ALWAYS
spring:
  application:
    name: test-task
  datasource:
    url: jdbc:postgresql://db:5432/walletsdb
    username: tester
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml